apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyxis-enzo-variablesentorno
  namespace: default
  labels:
     app: pyxis-enzo-variablesentorno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyxis-enzo-variablesentorno
  template:
    metadata:
      labels:
        app: pyxis-enzo-variablesentorno
    spec:
      containers:
      - name: pyxis-enzo-variablesentorno
        image: us.icr.io/capacitacion-pyxis/app-hpa:v3
        ports:
          - containerPort: 8080
        env:
          - name: NOMBRE
            valueFrom:
              secretKeyRef:
                name: variablesentorno-pyxis-enzo
                key: NOMBRE
---
apiVersion: v1
kind: Service
metadata:
  name: service-pyxis-enzo-variablesentorno
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pyxis-enzo-variablesentorno
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: route-pyxis-enzo-variablesentorno
    namespace: default
spec:
    to:
        kind: Service
        name: service-pyxis-enzo-variablesentorno